### ISSUE TITLE
Is this clCaffe the same with BVLC caffe's opencl branch?

### ISSUE THREAD

**Issue by kris-hu** [01org/caffe#18]
@gongzg 

Hi,

Is this clCaffe the same with BVLC caffe's opencl branch?

My environment is ubuntu14.04 64-bit and Intel® Core™ i7-4770 CPU @ 3.40GHz × 8 and HD Graphics. 
if I set USE_INTEL_SPATIAL := 0 in Makefile.config as default while compling, will it still use spatial conv but not GEMM?
Do you have performance reference using AlexNet as benchmark for the above environment?

Thanks

**Comment by gongzg** [comment]
@kris-hu yes, this repo's opencl branch is the same as BVLC's opencl branch. The clcaffe branch is out-of-date. If you set USE_INTEL_SPATIAL := 0, it will use GEMM instead of the direct convolution kernel. You need to enable USE_INTEL_SPATIAL if you want to try direct convolution engine.

I don't have performance number on HSW GT2 machine currently. I do have some performance number on a BDW GT3 machine. The performance number is at https://github.com/01org/caffe/wiki/clCaffe.

**Comment by kris-hu** [comment]
@gongzg 
In your performance reference above, is the batchsize equal to 256?
