### ISSUE TITLE
Transform Error

### ISSUE THREAD

**Issue by ChengzhiHuang** [01org/caffe#44]
I run the sample from "github.com/guoyilin/FaceDetection_CNN" , but when i test it ,it jumps out this error.
I also see this question : https://github.com/BVLC/caffe/issues/4964
What should I do ?

F0717 21:13:37.515277  8184 data_transformer.cpp:683] Check failed: cv_cropped_image.rows == data_mean_.height() (227 vs. 256) 

layer {
  name: "data"
  type: "ImageData"
  top: "data"
  top: "label"
  include {
    phase: TEST
  }
  transform_param {
    mirror: true
    crop_size: 227
    mean_file: "data/ilsvrc12/imagenet_mean.binaryproto"
  }
  image_data_param {
    source: "examples/FaceDetection_CNN/owndata/test.txt"
    batch_size: 50
    new_height: 256
    new_width: 256
  }
}

**Comment by gongzg** [comment]
I don't have the aflw data set so that I couldn't run the full test. I just tried to use caffe time to benchmark all the prototxts in the repository you specified, here are the results (using the fp16 version caffe):
deploy.prototxt:

build/tools/caffe-fp16.bin time -model ../FaceDetection_CNN/face_full_conv.prototxt  -gpu 0 -phase TEST
I0728 16:24:55.712425 30693 caffe-fp16.cpp:483] Average Forward pass: 18.7155 ms.
I0728 16:24:55.712453 30693 caffe-fp16.cpp:485] Average Backward pass: 0 ms.
I0728 16:24:55.712476 30693 caffe-fp16.cpp:487] Average Forward-Backward: 19.0328 ms.
I0728 16:24:55.712479 30693 caffe-fp16.cpp:489] Total Time: 951.638 ms.
I0728 16:24:55.712507 30693 caffe-fp16.cpp:490] *** Benchmark ends ***

face_full_conv.prototxt:
build/tools/caffe-fp16.bin time -model ../FaceDetection_CNN/face_full_conv.prototxt  -gpu 0 -phase TEST
I0728 16:27:33.888306 30707 caffe-fp16.cpp:483] Average Forward pass: 19.363 ms.
I0728 16:27:33.888334 30707 caffe-fp16.cpp:485] Average Backward pass: 0 ms.
I0728 16:27:33.888350 30707 caffe-fp16.cpp:487] Average Forward-Backward: 19.7082 ms.
I0728 16:27:33.888365 30707 caffe-fp16.cpp:489] Total Time: 985.408 ms.
I0728 16:27:33.888377 30707 caffe-fp16.cpp:490] *** Benchmark ends ***

I haven't met your issue. I'm using the inference-optimize branch.

**Comment by gongzg** [comment]
This issue is not likely a clCaffe issue, so I'm going to close this issue.
